use super::endpoint::Endpoint;
use super::super::{DstConnection, DstAddr, Path, resolver};
use super::super::connector::Connector;
use futures::{Future, Stream, Sink, Poll, Async, StartSend, AsyncSink, unsync};
use futures::sync::oneshot;
use ordermap::OrderMap;
use rand::{self, Rng};
use std::{cmp, io, net};
use std::cell::RefCell;
use std::collections::VecDeque;
use std::rc::Rc;
use tokio_core::reactor::Handle;
